#ifndef __GENERIX_DRIVER_COLORCODE_HPP__
#define __GENERIX_DRIVER_COLORCODE_HPP__

namespace Console {

enum Color
{
	BLACK, BLUE, GREEN, CYAN, RED, MAGENTA, BROWN, 
	LIGHTGRAY, DARKGRAY, LIGHTBLUE, LIGHTGREEN, 
	LIGHTCYAN, LIGHTRED, LIGHTMAGENTA, YELLOW, WHITE
};

}

#endif //__GENERIX_DRIVER_COLORCODE_HPP__
